// Auto-generated by scripts/scrape-udd.mjs
// Last updated: 2026-09-14T12:36:55.332Z
// Pages scraped: 12 | Articles: 26 | Failed: 0
// Run 'npm run scrape' to refresh this file
export const UDD_WEBSITE_CONTEXT = `

--- Source 1 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Build a future that moves with the world.
Discover career-ready programs, experienced mentors, and a student community designed to help you grow with purpose at Universidad de Dagupan.
Enroll now
Explore programs
42 years
of academic service
ISO 21001
certified education
Region 1
a recognized first
A campus built for possibility.
Learn, connect, and create your next chapter.
A campus built for possibility.
Learn, connect, and create your next chapter.
A campus built for possibility.
Learn, connect, and create your next chapter.
A campus built for possibility.
Learn, connect, and create your next chapter.
A campus built for possibility.
Learn, connect, and create your next chapter.
Find your program
Browse academic offerings
Institutional foundations
The principles that guide Universidad de Dagupan.
Our philosophy, vision, mission, and objectives define how we educate, serve, and contribute to the wider community.
Explore our academic programs
Philosophy
The institution believes that through education, man's God-given gifts are discovered and developed for his personal fulfillment and community uplift.
Vision
It Invisions to create a community responsive to the challenges of the changing world.
Mission
It is tasked to prepare the individuals with the best that education can offer in a manner that is consistent with the needs of society.
Objectives
Inculcate critical thinking; provide competent human resources; promote discipline, justice, and equality; improve quality of life through research and community service.
Quality commitment
EOMS Policy
The Universidad de Dagupan shall be known as an educational institution that discovers and develops God-given gifts to help achieve man's personal fulfillment and community uplift.
We shall continue to maintain our innovation efforts with the potential to create solutions and to be an invaluable national treasure. We shall commit to providing satisfactory service delivery and comply with applicable requirements in view of the educational, scientific, and technical developments.
We shall unceasingly improve our instruction, research, extension, and administrative operations to provide excellent education to individuals and communities responsive to the challenges of the changing world.
ISO 21001:2018-certified educational management system
Core Values
Competence
Unity
Dynamism
Dedication
Integrity
Teamwork
Campus updates
Stories and moments from UdD.
All news
All events
Jun 26, 2026
SDG 17 - PARTNERSHIPS FOR THE GOALS
Universidad de Dagupan Achieves Region I First as FoodSHAP Authorized Course Provider
𝗨𝗱𝗗 𝗯𝗲𝗰𝗼𝗺𝗲𝘀 𝗥𝗲𝗴𝗶𝗼𝗻 𝟭'𝘀 𝗳𝗶𝗿𝘀𝘁 𝗙𝗼𝗼𝗱𝗦𝗛𝗔𝗣 𝗔𝘂𝘁𝗵𝗼𝗿𝗶𝘇𝗲𝗱 𝗖𝗼𝘂𝗿𝘀𝗲 𝗣𝗿𝗼𝘃𝗶𝗱𝗲𝗿 Universidad de Dagupan (UdD) and FoodSHAP off...
Jun 2, 2026
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Strengthens Global Education Partnerships Through Courtesy Call with Philippine Ambassador to the UK
𝗨𝗱𝗗 𝗣𝗿𝗲𝘀𝗶𝗱𝗲𝗻𝘁 𝗷𝗼𝗶𝗻𝘀 𝗖𝗼𝘂𝗿𝘁𝗲𝘀𝘆 𝗖𝗮𝗹𝗹 𝘄𝗶𝘁𝗵 𝗣𝗵𝗶𝗹𝗶𝗽𝗽𝗶𝗻𝗲 𝗔𝗺𝗯𝗮𝘀𝘀𝗮𝗱𝗼𝗿 𝘁𝗼 𝘁𝗵𝗲 𝗨𝗻𝗶𝘁𝗲𝗱 𝗞𝗶𝗻𝗴𝗱𝗼𝗺 Universidad de Dagupan (UdD...
May 6, 2026
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Strengthens Global Reach Through MOU with National Chi Nan University of Taiwan
𝗨𝗱𝗗 𝘀𝗶𝗴𝗻𝘀 𝗠𝗢𝗨 𝘄𝗶𝘁𝗵 𝗡𝗮𝘁𝗶𝗼𝗻𝗮𝗹 𝗖𝗵𝗶 𝗡𝗮𝗻 𝗨𝗻𝗶𝘃𝗲𝗿𝘀𝗶𝘁𝘆 𝗼𝗳 𝗧𝗮𝗶𝘄𝗮𝗻 Universidad de Dagupan (UdD) entered into a Memorandu...
Apr 24, 2026
SDG 1 - ZERO HUNGER
fifth wave of udd ginhawa sa pasada project
𝗔𝘀 𝗽𝗮𝗿𝘁 𝗼𝗳 𝘁𝗵𝗲 𝗶𝗺𝗽𝗹𝗲𝗺𝗲𝗻𝘁𝗮𝘁𝗶𝗼𝗻 𝗼𝗳 𝘁𝗵𝗲 𝗡𝗦𝗧𝗣 𝗽𝗿𝗼𝗷𝗲𝗰𝘁, the Hospitality Management students, with the support of th...
Campus highlights
Recent events
Apr
12
Binibining Universidad de Dagupan 2024: The Grand Coronation
View event details
Apr
13
Hear the Roar of the Savannah! Universidad de Dagupan Cheerdance Competition 2024 Electrifies Universidad de Dagupan Intramurals
View event details
Mar
40 Years of UdD Excellence: UdD launches their first ever Coffee Table Book!
View event details
May
26
Universidad de Dagupan Steals the Spotlight at Higher Education Institution and Career Fair
View event details
Student achievement
Excellence that earns national recognition.
Meet Universidad de Dagupan graduates whose discipline and preparation led to outstanding board examination results.
View all topnotchers
Top 1
KATHERINE R. ESTRELLAS
Professional Teachers · May 2026
Top 3
ENGR. SAMUEL F. FLORES
Registered Electrical Engineers · April 2025
Top 4
ENGR. IMMANUEL GABRIEL N. PAPA
Electronics Technicians · April 2024
Visit the campus
Come see where your next chapter could begin.
Our campus is located in the heart of Dagupan City, with a community ready to welcome and guide you.
Universidad de Dagupan Arellano St., Pantal, Dagupan City, Pangasinan
Admissions support [email protected]
Contact the university
Ready when you are
Take the first step toward your UdD journey.
How to enroll
View programs


--- Source 2 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/programs

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Academic programs
Find the path that fits your ambition.
Explore the specialized colleges and
diverse academic offerings at Universidad de Dagupan designed for your professional future.
SCHOOL OF INFORMATION TECHNOLOGY
Degree Specifications
BACHELOR OF SCIENCE IN COMPUTER SCIENCE MAJOR IN DATA SCIENCE
BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY MAJOR IN WEB DEVELOPMENT
BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY MAJOR IN MULTIMEDIA ARTS
BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY MAJOR IN INFRASTRUCTURE W/ CYBERSECURITY
ETEAAP
VISIT COLLEGE MICROSITE
SCHOOL OF ENGINEERING
Degree Specifications
BACHELOR OF SCIENCE IN CIVIL ENGINEERING
BACHELOR OF SCIENCE IN COMPUTER ENGINEERING
BACHELOR OF SCIENCE IN ELECTRICAL ENGINEERING
BACHELOR OF SCIENCE IN ELECTRONIC ENGINEERING
SCHOOL OF TEACHER EDUCATION
Degree Specifications
BACHELOR OF EARLY CHILDHOOD EDUCATION
BACHELOR OF ELEMENTARY EDUCATION
BACHELOR OF SECONDARY EDUCATION MAJOR IN ENGLISH
BACHELOR OF SECONDARY EDUCATION MAJOR IN FILIPINO
BACHELOR OF SECONDARY EDUCATION MAJOR IN MATHEMATICS
BACHELOR OF SECONDARY EDUCATION MAJOR IN SCIENCE
BACHELOR OF SPECIAL NEEDS EDUCATION:GENERALIST
SCHOOL OF BUSINESS AND ACCOUNTANCY
Degree Specifications
BACHELOR OF SCIENCE IN ACCOUNTANCY
BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION MAJOR IN FINANCIAL MANAGEMENT
BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION MAJOR IN MARKETING MANAGEMENT
ETEEAP
SCHOOL OF INTERNATIONAL HOSPITALITY MANAGEMENT
Degree Specifications
BACHELOR OF SCIENCE IN TOURISM MANAGEMENT
BACHELOR OF SCIENCE IN HOSPITALITY MANAGEMENT
SCHOOL OF HUMANITIES
Degree Specifications
BACHELOR OF ARTS IN COMMUNICATION
BACHELOR OF SCIENCE IN PSYCHOLOGY
SCHOOL OF HEALTH AND SCIENCES
Degree Specifications
BACHELOR OF SCIENCE IN NURSING
SCHOOL OF BASIC EDUCATION
Degree Specifications
Course details coming soon.
SCHOOL OF CRIMINOLOGY
Degree Specifications
BACHELOR OF SCIENCE IN CRIMINOLOGY
SCHOOL OF PROFESSIONAL STUDIES
Degree Specifications
MASTER IN INFORMATION TECHNOLOGY
MASTER OF ARTS IN EDUCATION MAJOR IN EDUCATIONAL MANAGEMENT
MASTER OF BUSINESS ADMINISTRATION
DOCTOR OF BUSINESS ADMINISTRATION
DOCTOR OF PHILOSOPHY EDUCATIONAL LEADERSHIP AND MANAGEMENT


--- Source 3 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/enrollment

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Admissions guide
Your path to Universidad de Dagupan.
Follow these steps and prepare the essential
requirements for your journey at Universidad de Dagupan.
Requirements
Form 137
Form 138
Good Moral Character
PSA Birth Certificate
OTR Copy for UdD (Transferee)
A simple four-step guide
01
Enlistment
Submit requirements and initiate enlistment forms.
02
Admissions
Settle the required admission and initial tuition fees.
03
Scheduling
Get your subjects scheduled and secure registration.
04
Identification
Capture your official photo and receive school ID.
Begin your UdD journey
Our dedicated admissions team is
standing by to guide you through every phase of the enrollment process. Join a community built on a
42-year heritage of excellence.
CONNECT WITH ADMISSIONS
VIEW PROGRAMS


--- Source 4 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/contact-us

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Contact Universidad de Dagupan
How can we help?
Our administrative and academic
support teams are ready to provide the guidance you need.
Mailing Address
Arellano St., Pantal, Dagupan City, 2400,
Philippines
Direct Phone
(075)5232000
(075)5233000
+639452849061
Office
Hours (8am-5pm)
Email Reach
[email protected]
Office
Hours (8am-5pm)
Social Media
VISIT PROFILE


--- Source 5 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/allnews

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus stories
University news
June 26, 2026
Universidad de Dagupan Achieves Region I First as FoodSHAP Authorized Course Provider
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Staff
READ MORE
June 2, 2026
UdD Strengthens Global Education Partnerships Through Courtesy Call with Philippine Ambassador to the UK
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Staff
READ MORE
May 6, 2026
UdD Strengthens Global Reach Through MOU with National Chi Nan University of Taiwan
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Staff
READ MORE
April 24, 2026
fifth wave of udd ginhawa sa pasada project
SDG 1 - ZERO HUNGER
UdD Staff
READ MORE
April 22, 2026
UDD-SIHM Puts a Mindanaoan Twist on Dagupan Bangus, Clinches 3rd Place
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
April 14, 2026
Strengthening Futures: UdD and DMW-RO1 Unite for OFW and Student Development
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Staff
READ MORE
April 13, 2026
UDD Top’s among private higher education In 2026 UNIRANK
SDG 1 - QUALITY EDUCATION
UdD Staff
READ MORE
April 10, 2026
WAVE 3: UDD GINHAWA SA PASADA PROJECT
SDG 1 - ZERO HUNGER
UdD Staff
READ MORE
April 8, 2026
UDD Student Leaders Honor Dagupan Drivers Through Relief and Medical Mission on Araw ng Kagitingan
SDG 1 - GOOD HEALTH AND WELL BEING
UdD Staff
READ MORE
March 31, 2026
UDD Expands Community Care Through Medical Mission 2026
SDG 1 - GOOD HEALTH AND WELL BEING
UdD Staff
READ MORE
March 23, 2026
UDD STUDENT LEADERS LAUNCH THE “GINHAWA SA PASADA” PROJECT
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
March 19, 2026
UDD Receives Prestigious DSWD Special Citation as Development Partner
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
Latest Events
Apr 12
Binibining Universidad de Dagupan 2024: The Grand Coronation
Mar 01
Orientation for Freshmen and Transferees.
Dec 14
Light Up the Night! UdD Celebrate Our 2nd Uni Anni Lighting Ceremony
Jun 20
Maliket ya Agew na Dagupan!
Sep 09
Freshmen Kick-Off Orientation 2023: U Dare to Dream!
Stay
connected
Join our community newsletter and never miss an
update from UdD.
JOIN NOW


--- Source 6 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/feature

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Editor's choice
Featured stories and events
Discover the most impactful stories, groundbreaking events, and essential updates from across the Universidad de Dagupan community.
Featured news
SDG 17 - PARTNERSHIPS FOR THE GOALS
June 2, 2026
UdD Strengthens Global Education Partnerships Through Courtesy Call with Philippine Ambassador to the UK
𝗨𝗱𝗗 𝗣𝗿𝗲𝘀𝗶𝗱𝗲𝗻𝘁 𝗷𝗼𝗶𝗻𝘀 𝗖𝗼𝘂𝗿𝘁𝗲𝘀𝘆 𝗖𝗮𝗹𝗹 𝘄𝗶𝘁𝗵 𝗣𝗵𝗶𝗹𝗶𝗽𝗽𝗶𝗻𝗲 𝗔𝗺𝗯𝗮𝘀𝘀𝗮𝗱𝗼𝗿 𝘁𝗼 𝘁𝗵𝗲 𝗨𝗻𝗶𝘁𝗲𝗱 𝗞𝗶𝗻𝗴𝗱𝗼𝗺 Universidad de Dagupan (UdD) President Dr. Feliza Arzadon-Sua joined a courte...
READ FULL STORY
SDG 17 - PARTNERSHIPS FOR THE GOALS
May 6, 2026
UdD Strengthens Global Reach Through MOU with National Chi Nan University of Taiwan
𝗨𝗱𝗗 𝘀𝗶𝗴𝗻𝘀 𝗠𝗢𝗨 𝘄𝗶𝘁𝗵 𝗡𝗮𝘁𝗶𝗼𝗻𝗮𝗹 𝗖𝗵𝗶 𝗡𝗮𝗻 𝗨𝗻𝗶𝘃𝗲𝗿𝘀𝗶𝘁𝘆 𝗼𝗳 𝗧𝗮𝗶𝘄𝗮𝗻 Universidad de Dagupan (UdD) entered into a Memorandum of Understanding (MOU) with National Chi Nan Uni...
READ FULL STORY
SDG 1 - GOOD HEALTH AND WELL BEING
March 31, 2026
UDD Expands Community Care Through Medical Mission 2026
Building on our promise to bring healthcare closer to home, the Universidad de Dagupan Medical Mission 2026 has officially come to life! Following our launch of...
READ FULL STORY
SDG 5 - DECENT WORK AND ECONOMIC GROWTH
June 3, 2024
UdD first ever escalator
UdD Founder and Chairman of the Board, Dr. Voltaire P. Arzadon, spearheaded theinauguration of the first ever escalator of the campus.UdD stands out as the only...
READ FULL STORY
SDG 8 - REDUCED INEQUALITIES
September 23, 2022
UdD is PWD Friendly
By enhancing the facilities that meet their needs, UNIVERSIDAD DE DAGUPAN is facilitating the attendance of persons with disabilities (PWDs) in their classes.PW...
READ FULL STORY
SDG 1 - ZERO HUNGER
December 22, 2023
UdD Pamaskong Handog brings joy to families in Dagupan City
Universidad de Dagupan led by the Chairman of the board of trustees Dr. Voltaire P. Arzadon to witness the distribution of the donation for the selected familie...
READ FULL STORY
Update
March 28, 2023
UdD appoints Dr. Arzadon-Sua as new president
UdD appoints Dr. Arzadon-Sua as new presidentDr. Feliza Arzadon-Sua has been appointed as the new president of Universidad de Dagupan taking over the position f...
READ FULL STORY
Featured events
Campus
Apr 12
Binibining Universidad de Dagupan 2024: The Grand Coronation
READ MORE
Campus
Apr 13
Hear the Roar of the Savannah! Universidad de Dagupan Cheerdance Competition 2024 Electrifies Universidad de Dagupan Intramurals
READ MORE
Campus
Mar 09
40 Years of UdD Excellence: UdD launches their first ever Coffee Table Book!
READ MORE
Campus
Dec 18
UdD Celebrates 2nd Year as a University: Another Year of Recollection
READ MORE
Campus
Dec 14
Light Up the Night! UdD Celebrate Our 2nd Uni Anni Lighting Ceremony
READ MORE
Back to Campus Home


--- Source 7 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/topnotchers

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
TOPS
Student achievement
Board topnotchers
Celebrating Universidad de Dagupan students whose discipline, grit, and excellence earned national
recognition in professional licensing examinations.
Top 1
KATHERINE R. ESTRELLAS
Professional Teachers | May 2026
Top 3
ENGR. SAMUEL F. FLORES
Registered Electrical Engineers | April 2025
Top 4
ENGR. IMMANUEL GABRIEL N. PAPA
Electronics Technicians | April 2024
Top 10
VICTOR N. CAYAGO
Certified Public Accountants | May 2024
Top 2
ENGR. FRANZ FERNAND M. VELASCO
Electronics Technicians | April 2022
Top 4
ENGR. FRANZ FERNAND M. VELASCO
Electronics Engineers | April 2022
Top 7
ENGR. CHERISH ANTOINETTE A. FERRER
Electronics Engineers | October 2019
Top 2
ENGR. HANNAH JOY D. FADULLON
Electronics Engineers | October 2019
Top 8
ENGR. FERREN M. VELASCO
Electronics Engineers | October 2018
Top 6
ENGR. RONNIE GEE G. ALFONSO
Electronics Engineers | October 2017
Top 8
ADRIEL M. VELASCO
Certified Public Accountants | October 2015
Top 1
RALLEY S. PARAGAS
Certified Public Accountants | October 2015
Top 10
CARELEA F. RIMORIN
Professional Teachers | August 2014
Top 6
ENGR. MARVIN COLUMBINO
Electronics Technicians | April 2013
Top 4
ENGR. NEIL EFREN VILLANUEVA
Registered Master Electricians | April 2013
Top 4
MARK FRANCIS CAGAOAN
Certified Public Accountants | October 2012
Top 9
ELLEN MAY T. LIM
Professional Teachers | September 2011
Top 10
RUBY ANN PRADO
Nurses | December 2010
Top 6
RIZZA A. TAMAYO
Nurses | June 2008


--- Source 8 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/allevents

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus calendar
University events
April 13, 2024
Hear the Roar of the Savannah! Universidad de Dagupan Cheerdance Competition 2024 Electrifies Universidad de Dagupan Intramurals
Campus
UdD Staff
READ MORE
April 12, 2024
Binibining Universidad de Dagupan 2024: The Grand Coronation
Campus
UdD Staff
READ MORE
March 9, 2024
40 Years of UdD Excellence: UdD launches their first ever Coffee Table Book!
Campus
UdD Staff
READ MORE
December 18, 2023
UdD Celebrates 2nd Year as a University: Another Year of Recollection
Campus
UdD Staff
READ MORE
December 14, 2023
Light Up the Night! UdD Celebrate Our 2nd Uni Anni Lighting Ceremony
Campus
UdD Staff
READ MORE
December 13, 2023
Pamaskong Handog 2023: Spreading Holiday Cheer One Blessing at a Time.
Campus
UdD Staff
READ MORE
September 9, 2023
Freshmen Kick-Off Orientation 2023: U Dare to Dream!
Campus
UdD Staff
READ MORE
June 20, 2023
Maliket ya Agew na Dagupan!
Campus
Administrator
READ MORE
May 26, 2023
Universidad de Dagupan Steals the Spotlight at Higher Education Institution and Career Fair
Campus
UdD Staff
READ MORE
March 11, 2023
Filipino's spirit of giving will always prevail
Campus
Administrator
READ MORE
March 1, 2023
Orientation for Freshmen and Transferees.
Campus
Administrator
READ MORE
Latest News
May 13
Respect
Jul 14
UdD and DepEd SDO-Dagupan Forge Partnership for ReNuVal Bayanihan Project
Nov 28
Universidad de Dagupan School of Health Sciences achieved its 100% passing rate
Jan 10
Universidad de Dagupan School of Information Technology Education formally announces its partnership with the Palo Alto Networks Cybersecurity Academy
Mar 23
UDD STUDENT LEADERS LAUNCH THE “GINHAWA SA PASADA” PROJECT
Join the
momentum
Experience the dynamic campus life at Universidad de Dagupan.
ENROLL NOW


--- Source 9 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/allnews?page=2

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus stories
University news
March 2, 2026
UDD Leaders Attend REACH Study Program in Singapore
SDG 1 - QUALITY EDUCATION
UdD Staff
READ MORE
February 16, 2026
DOST - UDD iHub Launched, Marking First Innovation Hub in Pangasinan
SDG 9 - INDUSTRY INNOVATION AND INFRASTRUCTURE
UdD Staff
READ MORE
February 13, 2026
Koro Universidad de Dagupan enlivens EU–ASEAN welcome dinner
SDG 5 - DECENT WORK AND ECONOMIC GROWTH
UdD Staff
READ MORE
January 31, 2026
DOST-IR, UdD Forge Partnership to Establish Innovation Hub
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Staff
READ MORE
January 31, 2026
DepEd SDO Dagupan City, UdD Partner to Strengthen SPSTEM and Robotics Education
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Staff
READ MORE
January 20, 2026
Presidential Scholarship Exam Results (Batch 1)
SDG 1 - QUALITY EDUCATION
UdD Staff
READ MORE
January 10, 2026
Universidad de Dagupan School of Information Technology Education formally announces its partnership with the Palo Alto Networks Cybersecurity Academy
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Staff
READ MORE
December 19, 2025
Congratulations to our Newly Licensed Teachers from the Universidad de Dagupan!
SDG 1 - QUALITY EDUCATION
UdD Staff
READ MORE
December 3, 2025
Universidad de Dagupan is honored to be recognized as one of the awardees in the 𝗖𝗛𝗘𝗗 𝗜𝗖𝗢𝗡𝗦 𝗔𝘄𝗮𝗿𝗱𝘀 𝟮𝟬𝟮𝟱
SDG 1 - QUALITY EDUCATION
UdD Staff
READ MORE
December 3, 2025
Universidad de Dagupan to Offer Adobe Creative Cloud Access to Students and Faculty
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Staff
READ MORE
November 27, 2025
Universidad de Dagupan Recommended for ISO 21001:2018 Certificate Maintenance
Update
UdD Staff
READ MORE
November 27, 2025
UDD Nursing achieved 92.65% passing rate!
SDG 1 - QUALITY EDUCATION
UdD Staff
READ MORE
Latest Events
Jun 20
Maliket ya Agew na Dagupan!
May 26
Universidad de Dagupan Steals the Spotlight at Higher Education Institution and Career Fair
Mar 09
40 Years of UdD Excellence: UdD launches their first ever Coffee Table Book!
Mar 01
Orientation for Freshmen and Transferees.
Dec 18
UdD Celebrates 2nd Year as a University: Another Year of Recollection
Stay
connected
Join our community newsletter and never miss an
update from UdD.
JOIN NOW


--- Source 10 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/allnews?page=3

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus stories
University news
November 24, 2025
UdD Joins PSU in Hosting ICTSBAF 2025, Strengthening Academic and Research Collaboration
SDG 1 - QUALITY EDUCATION
UdD Staff
READ MORE
November 12, 2025
Partnership of Adobe and UDD
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Staff
READ MORE
October 30, 2025
Universidad de Dagupan (UdD) and Pangasinan State University (PSU) proudly raised the Philippine flag on the global stage after winning 4th place out of 17 countries
SDG 9 - INDUSTRY INNOVATION AND INFRASTRUCTURE
UdD Staff
READ MORE
September 20, 2025
SITE UDD partners with GDAP
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Staff
READ MORE
September 5, 2025
UdD Joins CHED High-Level Delegation on Possible Collaboration with Tokyo Metropolitan University
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Staff
READ MORE
August 30, 2025
Congratulations to our entire batch of 2025 Bachelor of Science in Psychology graduates for successfully passing the recent Certified Human Resource Associate (CHRA) Assessment Examination!
SDG 1 - QUALITY EDUCATION
UdD Staff
READ MORE
August 28, 2025
Universidad de Dagupan has been ranked as the Top 1 Private Higher Education Institution in Pangasinan in the 2025 uniRank University Ranking
SDG 1 - QUALITY EDUCATION
UdD Staff
READ MORE
August 15, 2025
Skills Enhancement 5-Day Reception and Training Program for Incoming Criminology Interns
SDG 16 - PEACE, JUSTICE AND STRONG INSTITUTIONS
UdD Staff
READ MORE
August 12, 2025
Kindness
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
August 8, 2025
Compassion
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
July 30, 2025
Humility
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
July 28, 2025
The Supreme Student Council of Universidad de Dagupan, together with the Student Affairs Office, is actively preparing relief packs for those affected by the typhoon.
SDG 1 - ZERO HUNGER
UdD Staff
READ MORE
Latest Events
Mar 09
40 Years of UdD Excellence: UdD launches their first ever Coffee Table Book!
Dec 14
Light Up the Night! UdD Celebrate Our 2nd Uni Anni Lighting Ceremony
Dec 18
UdD Celebrates 2nd Year as a University: Another Year of Recollection
Jun 20
Maliket ya Agew na Dagupan!
Mar 01
Orientation for Freshmen and Transferees.
Stay
connected
Join our community newsletter and never miss an
update from UdD.
JOIN NOW


--- Source 11 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/allnews?page=4

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus stories
University news
July 28, 2025
The Supreme Student Council of Universidad de Dagupan, together with the Student Affairs Office, is actively preparing relief packs for those affected by the typhoon.
Update
UdD Staff
READ MORE
July 28, 2025
First Batch of Project Kalinga Delivered!
SDG 1 - ZERO HUNGER
UdD Staff
READ MORE
July 23, 2025
Honesty
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
July 18, 2025
Generosity
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
July 14, 2025
UdD and DepEd SDO-Dagupan Forge Partnership for ReNuVal Bayanihan Project
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Staff
READ MORE
July 14, 2025
UdD and DepEd SDO-Dagupan Forge Partnership for ReNuVal Bayanihan Project
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Staff
READ MORE
July 13, 2025
Empathy
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
July 12, 2025
Universidad de Dagupan made it to the 2025 World University Rankings for Innovation (WURI)
SDG 1 - QUALITY EDUCATION
UdD Staff
READ MORE
July 2, 2025
Universidad de Dagupan successfully conducted an earthquake and fire drill
SDG 16 - PEACE, JUSTICE AND STRONG INSTITUTIONS
UdD Staff
READ MORE
July 1, 2025
Discipline
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
June 26, 2025
Courtesy
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
June 24, 2025
Universidad de Dagupan was honored as one of the 113 Philippine Higher Education Institutions recognized in the 2025 Times Higher Education Impact Rankings
SDG 1 - QUALITY EDUCATION
UdD Staff
READ MORE
Latest Events
Mar 01
Orientation for Freshmen and Transferees.
Dec 14
Light Up the Night! UdD Celebrate Our 2nd Uni Anni Lighting Ceremony
May 26
Universidad de Dagupan Steals the Spotlight at Higher Education Institution and Career Fair
Dec 18
UdD Celebrates 2nd Year as a University: Another Year of Recollection
Mar 11
Filipino's spirit of giving will always prevail
Stay
connected
Join our community newsletter and never miss an
update from UdD.
JOIN NOW


--- Source 12 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/allnews?page=5

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus stories
University news
June 20, 2025
Universidad de Dagupan joins the 78th Araw ng Dagupan Tree Planting Activity
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
June 18, 2025
Universidad de Dagupan proudly makes it to the Times Higher Education Impact Rankings 2025
SDG 1 - QUALITY EDUCATION
UdD Staff
READ MORE
June 18, 2025
Courage
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
June 9, 2025
Appreciation
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
June 4, 2025
Accountability
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
June 2, 2025
Anchovia: From Tradition to Innovation — A Journey Toward Sustainable Food Solutions
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
May 30, 2025
In the effort to sustain the gains of the program, a collaborative meeting was conducted between DSWD Field Office 1 - Ilocos Region (DSWD FO 1) Pantawid Pamilyang Pilipino Program (4Ps) Division and the Universidad de Dagupan (UDD)
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Staff
READ MORE
May 30, 2025
Unity
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
May 22, 2025
Universidad de Dagupan is now an official signatory of The SDG Accord
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Staff
READ MORE
May 21, 2025
Teamwork
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
May 13, 2025
Respect
SDG 15 - LIFE ON LAND
UdD Staff
READ MORE
May 12, 2025
BA Communication students of Universidad de Dagupan took part in the special coverage of Eleksyon 2025 with GMA Integrated News!
SDG 16 - PEACE, JUSTICE AND STRONG INSTITUTIONS
UdD Staff
READ MORE
Latest Events
Apr 13
Hear the Roar of the Savannah! Universidad de Dagupan Cheerdance Competition 2024 Electrifies Universidad de Dagupan Intramurals
Mar 09
40 Years of UdD Excellence: UdD launches their first ever Coffee Table Book!
May 26
Universidad de Dagupan Steals the Spotlight at Higher Education Institution and Career Fair
Jun 20
Maliket ya Agew na Dagupan!
Dec 13
Pamaskong Handog 2023: Spreading Holiday Cheer One Blessing at a Time.
Stay
connected
Join our community newsletter and never miss an
update from UdD.
JOIN NOW


--- Source 13 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/128

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
SDG 17 - PARTNERSHIPS FOR THE GOALS
Universidad de Dagupan Achieves Region I First as FoodSHAP Authorized Course Provider
By UdD Staff
Jun 26, 2026
Share
𝗨𝗱𝗗 𝗯𝗲𝗰𝗼𝗺𝗲𝘀 𝗥𝗲𝗴𝗶𝗼𝗻 𝟭'𝘀 𝗳𝗶𝗿𝘀𝘁 𝗙𝗼𝗼𝗱𝗦𝗛𝗔𝗣 𝗔𝘂𝘁𝗵𝗼𝗿𝗶𝘇𝗲𝗱 𝗖𝗼𝘂𝗿𝘀𝗲 𝗣𝗿𝗼𝘃𝗶𝗱𝗲𝗿
Universidad de Dagupan (UdD) and FoodSHAP officially signed a Memorandum of Agreement (MOA), making UdD the first institution in Region I to become a FoodSHAP Authorized Course Provider. The partnership marks a significant milestone in advancing food safety education in the region while reinforcing the University's commitment to producing globally competitive professionals. Representing the institutions were UdD President Dr. Feliza Arzadon-Sua and FoodSHAP Managing Director Elsie Gatpayat, FSCO.
The agreement formally authorizes UdD to offer the Food Safety Training & Examination System (FSTES) Programs leading to FoodSHAP Qualifications, providing students and industry practitioners with access to internationally recognized food safety certifications. The partnership recognizes FoodSHAP as the national provider of the Food Safety Training & Examination System (FSTES), responsible for authorizing institutions to deliver course programs leading to FoodSHAP Qualifications. As the first institution in Region I to establish this partnership, UdD further strengthens its role as a leader in delivering industry-aligned education and workforce development initiatives. Also present during the signing were Dr. Justin Frances Q. Callesto, UdD Vice President for Administration and Finance and Dean of the School of International Hospitality Management; Mr. John Marc Lomibao, Program Head of the School of International Hospitality Management; and Ms. KC Cadano-Salcedo, FSCO, FoodSHAP Program Partnership Manager.
The collaboration reflects both institutions' shared commitment to promoting excellence in food safety education through accessible, competency-based training and certification programs. By becoming a FoodSHAP Authorized Course Provider, UdD expands learning opportunities that enhance professional competence, uphold food safety standards, and prepare graduates for careers in the hospitality, food service, and allied industries. The MOA signing was held today at Primeland Building, Market Street, Madrigal Business Park, Ayala Alabang, Muntinlupa City, marking another milestone in Universidad de Dagupan's pursuit of academic excellence and strategic industry partnerships.
Back to All News


--- Source 14 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/127

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Strengthens Global Education Partnerships Through Courtesy Call with Philippine Ambassador to the UK
By UdD Staff
Jun 2, 2026
Share
𝗨𝗱𝗗 𝗣𝗿𝗲𝘀𝗶𝗱𝗲𝗻𝘁 𝗷𝗼𝗶𝗻𝘀 𝗖𝗼𝘂𝗿𝘁𝗲𝘀𝘆 𝗖𝗮𝗹𝗹 𝘄𝗶𝘁𝗵 𝗣𝗵𝗶𝗹𝗶𝗽𝗽𝗶𝗻𝗲 𝗔𝗺𝗯𝗮𝘀𝘀𝗮𝗱𝗼𝗿 𝘁𝗼 𝘁𝗵𝗲 𝗨𝗻𝗶𝘁𝗲𝗱 𝗞𝗶𝗻𝗴𝗱𝗼𝗺
Universidad de Dagupan (UdD) President Dr. Feliza Arzadon-Sua joined a courtesy call and meeting with Philippine Ambassador to the United Kingdom, Teodoro L. Locsin Jr., as part of the Philippine delegation's engagements in London. During the meeting, discussions centered on educational opportunities for Overseas Filipino Workers (OFWs) in the United Kingdom, particularly the Expanded Tertiary Education Equivalency and Accreditation Program (ETEEAP).
The program provides qualified working professionals with the opportunity to earn a college degree by recognizing their prior learning, work experience, and competencies. The meeting highlighted the importance of making higher education more accessible to Filipinos abroad and strengthening initiatives that support lifelong learning and professional advancement for OFWs.
Back to All News


--- Source 15 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/126

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
SDG 17 - PARTNERSHIPS FOR THE GOALS
UdD Strengthens Global Reach Through MOU with National Chi Nan University of Taiwan
By UdD Staff
May 6, 2026
Share
𝗨𝗱𝗗 𝘀𝗶𝗴𝗻𝘀 𝗠𝗢𝗨 𝘄𝗶𝘁𝗵 𝗡𝗮𝘁𝗶𝗼𝗻𝗮𝗹 𝗖𝗵𝗶 𝗡𝗮𝗻 𝗨𝗻𝗶𝘃𝗲𝗿𝘀𝗶𝘁𝘆 𝗼𝗳 𝗧𝗮𝗶𝘄𝗮𝗻 Universidad de Dagupan (UdD) entered into a Memorandum of Understanding (MOU) with National Chi Nan University today, marking a significant step in strengthening international academic collaboration. The signing took place during Day 1 of the 6th HLU Annual Conference, held alongside the 2026 WURI Global Rankings Ceremony from May 6–8.
The MOU establishes a framework for cooperation between the two institutions in areas such as joint research and academic activities, faculty and student exchanges, and the sharing of academic resources and research publications. It also opens opportunities for study tours, joint degree programs (subject to separate agreements), and broader multilateral collaborations. Representing UdD in this milestone engagement was Chief Operating Officer Jann Alfred Arzadon Quinto, who underscored the university’s commitment to expanding its global academic partnerships and enhancing the quality of education through international linkages.
The agreement aligns with both institutions’ shared vision of fostering innovation, academic excellence, and cross-cultural exchange. It also reflects a mutual commitment to inclusivity, equal opportunity, and collaborative growth in higher education. The joint event gathered more than 350 higher education leaders from across the globe, serving as a premier platform for discussions on university innovation, artificial intelligence transformation, sustainability, and global collaboration.
Through this partnership, UdD continues to position itself as an active participant in the global academic community.
Back to All News


--- Source 16 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/125

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
SDG 1 - ZERO HUNGER
fifth wave of udd ginhawa sa pasada project
By UdD Staff
Apr 24, 2026
Share
𝗔𝘀 𝗽𝗮𝗿𝘁 𝗼𝗳 𝘁𝗵𝗲 𝗶𝗺𝗽𝗹𝗲𝗺𝗲𝗻𝘁𝗮𝘁𝗶𝗼𝗻 𝗼𝗳 𝘁𝗵𝗲 𝗡𝗦𝗧𝗣 𝗽𝗿𝗼𝗷𝗲𝗰𝘁, the Hospitality Management students, with the support of the Supreme Student Council, led a meaningful pansit drive under the Ginhawa sa Pasada Project—continuing its advocacy of providing comfort, care, and support to our hardworking PUV drivers.
This initiative serves as a heartfelt expression of service and compassion, where every meal shared carries sincere gratitude and appreciation for the drivers’ dedication and tireless service on the road.
More than just a feeding activity, this 𝗡𝗦𝗧𝗣-𝗱𝗿𝗶𝘃𝗲𝗻 𝗶𝗻𝗶𝘁𝗶𝗮𝘁𝗶𝘃𝗲 reflects the true spirit of bayanihan and social responsibility. It showcases how students can transform knowledge into meaningful action—serving the community with purpose, unity, and a shared commitment to make a difference.
Back to All News


--- Source 17 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/events/12

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus
Binibining Universidad de Dagupan 2024: The Grand Coronation
By UdD Staff
April 12, 2024
Share
The Universidad de Dagupan (UdD) recently held its much-anticipated Binibining Universidad de Dagupan 2024 pageant, a night filled with beauty, grace, and intelligence. The event was a resounding success, showcasing the talent and potential of UdD's binibinis.
The pageant saw a group of talented and confident young women compete in various segments, including evening gown, best in production number, question-and-answer, and a lot more. Each contestant displayed their unique strengths and personalities, captivating the audience with their poise, eloquence, and passion. Amongst those young and beautiful women was the one and only, Miss Earth Air 2023, Yllana Marie Aduana, who lent her expertise and inspiration to the aspiring beauty queens as one of the special guest judges of the night.
The whole gymnasium cheered with excitement and anticipation as the judges punctiliously select a worthy successor to the Binibining Universidad de Dagupan crown.
After a dazzling display of brilliance and poise, the esteemed judges finally awarded the prestigious crown to the radiant Allyssa Marie Tucay, from the esteemed School of Business and Accountancy, crowning her Binibining Universidad de Dagupan 2024. Of course, the one crowning her is none other than Donna Rein Nuguid, who was Binibining Universidad de Dagupan 2023, also reigning from the School of Business and Accountancy. The momentous night continued as other impressive awards were presented to the participants, recognizing their incredible talents and achievements.
Beyond the glitz and glamor, the Binibining Universidad de Dagupan pageant served as a platform for empowering young women. The contestants not only showcased their beauty and talent but also advocated for various social causes and demonstrated their commitment to academic excellence and community service.
The event concluded with a sense of pride and accomplishment for all involved. The newly crowned Binibining Universidad de Dagupan and her court will undoubtedly serve as inspiring role models for the UdD community, promoting confidence, leadership, and a dedication to making a positive impact on the world.
Photo courtesy: Kurt Denzel A. Caranyagan
Back to All Events


--- Source 18 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/events/11

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus
Hear the Roar of the Savannah! Universidad de Dagupan Cheerdance Competition 2024 Electrifies Universidad de Dagupan Intramurals
By UdD Staff
April 13, 2024
Share
Hear the Roar of the Savannah! Universidad de Dagupan Cheerdance Competition 2024 Electrifies Universidad de Dagupan Intramurals
The Universidad de Dagupan Intramurals 2024 roared with excitement as the Cheerdance Competition 2024 took center stage. The event showcased the athleticism, teamwork, and vibrant spirit of the UdD community, leaving the audience in awe with electrifying performances.
Competing teams brought their best, displaying intricate formations, synchronized stunts, and high-energy routines. The atmosphere was electric as cheers erupted from the crowd, each team vying for the coveted championship title.
The competition served as a platform for students to showcase their talents and dedication to their respective colleges and departments. The synchronized movements, powerful stunts, and infectious enthusiasm were a testament to the hard work and commitment of each team.
Beyond the competitive spirit, the Cheerdance Competition fostered a sense of unity and camaraderie within the UdD community. Students came together to support their teams, creating a vibrant and energetic atmosphere that transcended departmental boundaries.
As the competition concluded, the judges crowned the champions, recognizing the outstanding performances and unwavering dedication of The School of Information Technology Education (SITE) , solidifying their reign as back-to-back champions from last year's cheerdance competition. The crowd erupted in a thunderous roar as SITE students celebrated their victory. The event left a lasting impression on everyone involved, further solidifying the importance of teamwork, sportsmanship, and school spirit within the UdD community.
Photo courtesy: Kurt Denzel A. Caranyagan
Back to All Events


--- Source 19 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/events/10

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus
40 Years of UdD Excellence: UdD launches their first ever Coffee Table Book!
By UdD Staff
March 9, 2024
Share
The University of Dagupan (UdD) is celebrating its 40th anniversary in grand style with the launch of its very first coffee table book! This commemorative publication promises to be a visual and historical journey through the institution's remarkable journey, showcasing its achievements, milestones, and the impact it has made on the community.
Since its establishment in 1984, UdD has grown from a small college to a full-fledged university, consistently striving for academic excellence and fostering a vibrant campus culture. The coffee table book will serve as a testament to this growth, capturing the essence of UdD's legacy through captivating photographs, insightful stories, and detailed accounts of its evolution.
This special publication is expected to be a valuable resource for students, alumni, faculty, and the wider community. It will offer a glimpse into UdD's rich history, highlighting the dedication of its founders, the contributions of its faculty and staff, and the achievements of its students.
The launch of the coffee table book marks a significant moment for UdD, not only commemorating its 40th Ruby anniversary but also providing a tangible record of its journey and accomplishments. This visually stunning publication is sure to become a cherished keepsake for everyone connected to the university, serving as a source of inspiration and pride for generations to come.
photo courtesy: Landeil M. Robles
Back to All Events


--- Source 20 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/events/9

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus
Universidad de Dagupan Steals the Spotlight at Higher Education Institution and Career Fair
By UdD Staff
May 26, 2023
Share
The Universidad de Dagupan (UdD) made a resounding impact at the recent Higher Education Institution (HEI) Career Fair held at the CSI Stadia in Dagupan City. Themed "Tagumpay Mo Kabataan, Pangarap ng Dagupan" (Your Success, Dagupan's Dream), the two-day event provided a valuable platform for graduating high school students to explore their academic options and connect with potential career paths.
UdD wasn't alone in its mission. The fair bustled with energy as numerous colleges and universities from the region showcased their diverse academic programs. Informative booths and engaging presentations offered students a glimpse into various fields of study, from engineering and business to medicine and the arts.
UdD's delegation showcased the university's diverse academic programs through interactive booths and presentations. Faculty members and current students engaged with the enthusiastic crowd, answering questions about admissions, scholarships, and student life.
UdD's participation in the HEI Career Fair went beyond simply promoting its programs. The university actively contributed to the event's mission of empowering young minds. By providing insightful guidance and showcasing its vibrant campus culture, UdD made a lasting impression on future generations, inspiring them to pursue their academic aspirations and contribute to the city's bright future.
Back to All Events


--- Source 21 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/124

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
SDG 15 - LIFE ON LAND
UDD-SIHM Puts a Mindanaoan Twist on Dagupan Bangus, Clinches 3rd Place
By UdD Staff
Apr 22, 2026
Share
Huge congratulations to our talented culinary team from the 𝐔𝐧𝐢𝐯𝐞𝐫𝐬𝐢𝐝𝐚𝐝 𝐝𝐞 𝐃𝐚𝐠𝐮𝐩𝐚𝐧 – 𝐒𝐜𝐡𝐨𝐨𝐥 𝐨𝐟 𝐈𝐧𝐭𝐞𝐫𝐧𝐚𝐭𝐢𝐨𝐧𝐚𝐥 𝐇𝐨𝐬𝐩𝐢𝐭𝐚𝐥𝐢𝐭𝐲 𝐌𝐚𝐧𝐚𝐠𝐞𝐦𝐞𝐧𝐭 𝐟𝐨𝐫 𝐬𝐞𝐜𝐮𝐫𝐢𝐧𝐠 𝟑𝐫𝐝 𝐏𝐥𝐚𝐜𝐞 in one of the city's most prestigious and highly anticipated annual cooking competitions!
Representing the University with pride and passion:
- 𝐎𝐥𝐢𝐯𝐞 𝐅𝐚𝐲𝐞 𝐋𝐨𝐫𝐞𝐳𝐜𝐨
- 𝐑𝐚𝐩𝐡𝐚𝐞𝐥 𝐀𝐪𝐮𝐢𝐧𝐨
- 𝐌𝐚𝐭𝐭 𝐌𝐜𝐜𝐨𝐲 𝐉𝐮𝐧𝐭𝐨
- 𝐌𝐚𝐤𝐢𝐬𝐢𝐠 𝐌𝐨𝐧𝐭𝐨𝐲𝐚
The Winning Concept: A Mindanaoan Twist on Dagupan’s Best Our team took the humble Dagupan Bangus on a journey to Northern Mindanao. They showcased the incredible versatility of the milkfish through their signature 𝓑𝓪𝓷𝓰𝓾𝓼 𝓟𝓲𝓪𝓹𝓪𝓻𝓪𝓷, elevated by the bold, spicy kick of Palapa. The Main: Bangus Piaparan paired perfectly with aromatic Pineapple Fried Rice. The team demonstrated that this dish isn't just for formal dining—it’s also a soul-satisfying street food when paired with Roti. In addition, the team served a creative Ensalada featuring coconut strips, green mango, and pineapple, designed to create an "explosive" burst of freshness in every bite.
The Journey Continues While the heat in the kitchen was intense, our students embraced every second of the challenge. This 3rd-place finish is more than just a trophy—it’s a testament to their creativity and teamwork. Cheers to our future chefs! Thank you for putting UdD-SIHM on the culinary map!
Back to All News


--- Source 22 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/123

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
SDG 17 - PARTNERSHIPS FOR THE GOALS
Strengthening Futures: UdD and DMW-RO1 Unite for OFW and Student Development
By UdD Staff
Apr 14, 2026
Share
𝗨𝗱𝗗, 𝗗𝗠𝗪-𝗥𝗢𝟭 𝗳𝗼𝗿𝗴𝗲 𝗽𝗮𝗿𝘁𝗻𝗲𝗿𝘀𝗵𝗶𝗽 𝘁𝗼 𝘀𝘂𝗽𝗽𝗼𝗿𝘁 𝗢𝗙𝗪𝘀 𝗮𝗻𝗱 𝘀𝘁𝘂𝗱𝗲𝗻𝘁𝘀
Universidad de Dagupan (UdD) and the Department of Migrant Workers Regional Office I (DMW-RO1) officially signed a Memorandum of Agreement, marking UdD as the 𝗳𝗶𝗿𝘀𝘁 𝗛𝗶𝗴𝗵𝗲𝗿 𝗘𝗱𝘂𝗰𝗮𝘁𝗶𝗼𝗻 𝗜𝗻𝘀𝘁𝗶𝘁𝘂𝘁𝗶𝗼𝗻 (𝗛𝗘𝗜) 𝗶𝗻 𝗥𝗲𝗴𝗶𝗼𝗻 𝟭 to establish a formal partnership with the agency.
The collaboration highlights a shared commitment to advancing education, employability, and support services for Overseas Filipino Workers (OFWs) and their families. Representing the institutions were UdD President Dr. Feliza Valorie Arzadon-Sua and DMW-RO1 Regional Director Christian Rey O. Sison. The agreement centers on creating opportunities that will benefit both students and OFWs through programs focused on workforce readiness and public service.
Also present during the signing were Mr. Jerome A. Alcantara, Assistant Secretary of the Department of Migrant Workers; Ms. Rhodora Dingle, Senior Labor Employment Officer of the DOLE Central Pangasinan Field Office; Jocelyn Z. Siapno, PESO Manager; and Dagupan City Mayor Belen T. Fernandez. Key provisions of the MOA include internship placements for students within DMW offices, joint campaigns on anti-illegal recruitment and trafficking in persons, and collaboration in job fairs and career-related initiatives.
These efforts aim to equip students with practical experience while strengthening awareness and protection mechanisms for OFWs. UdD also reaffirmed its commitment to providing accessible, relevant, and flexible education for OFWs and their dependents. In turn, DMW-RO1 will provide technical expertise, supervision, and program support, ensuring the effective implementation of joint initiatives.
The MOA signing was held today at CSI The City Mall in Dagupan City as part of the Bangus Festival Mega Job Fair
Back to All News


--- Source 23 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/122

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
SDG 1 - QUALITY EDUCATION
UDD Top’s among private higher education In 2026 UNIRANK
By UdD Staff
Apr 13, 2026
Share
Universidad de Dagupan proudly ranks 𝗧𝗼𝗽 𝟭 among private higher education institutions in Pangasinan and 𝗧𝗼𝗽 𝟴 in the Ilocos Region in the 𝟮𝟬𝟮𝟲 𝗨𝗻𝗶𝗥𝗮𝗻𝗸 𝗨𝗻𝗶𝘃𝗲𝗿𝘀𝗶𝘁𝘆 𝗥𝗮𝗻𝗸𝗶𝗻𝗴. This recognition is based on UniRank’s criteria, including university accreditation, valid degree offerings, and strong online presence and impact. The achievement reflects the university’s commitment to quality education and innovation.
Back to All News


--- Source 24 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/121

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
SDG 1 - ZERO HUNGER
WAVE 3: UDD GINHAWA SA PASADA PROJECT
By UdD Staff
Apr 10, 2026
Share
The Supreme Student Council once again took to the streets of Dagupan to carry forward the “Ginhawa sa Pasada” project—an initiative of Universidad de Dagupan aimed at extending support to our hardworking jeepney and tricycle drivers during these challenging times. In response to the ongoing oil crisis, the project provided fresh chicken from Arzadon Farm and medical assistance to help ease the financial burden of our local drivers.
Special thanks to UDD staff, Nightingale Society, CPR, and Arzadon Farm for making this initiative possible.
We believe that leadership is not measured by titles, but by service. Though this may seem like a small gesture, we hope it inspires a greater movement—one that amplifies the voices and promotes the welfare of our local drivers.
This meaningful initiative was carried out in collaboration with the founder of Universidad de Dagupan, Dr. Voltaire P. Arzadon, together with Dr. Loreta C. Arzadon, Chief Operating Officer, Mr. Jann Alfred A. Quinto, Supreme Student Council, Adviser Ma’am May Jacklyn R. Samson, and University President, Dr. Feliza Arzadon-Sua. Our heartfelt gratitude is also extended to the entire UDD Administration for their unwavering support.
Back to All News


--- Source 25 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/120

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
SDG 1 - GOOD HEALTH AND WELL BEING
UDD Student Leaders Honor Dagupan Drivers Through Relief and Medical Mission on Araw ng Kagitingan
By UdD Staff
Apr 8, 2026
Share
Sa paggunita sa "𝗔𝗿𝗮𝘄 𝗻𝗴 𝗞𝗮𝗴𝗶𝘁𝗶𝗻𝗴𝗮𝗻," ang ating mga student leaders ng Universidad de Dagupan ay nag bahagi ng kanilang suporta para sa ating mga Hari ng Kalsada sa Lungsod ng Dagupan ng relief kits—isang munting handog ng pasasalamat sa kanilang walang sawang serbisyo sa araw-araw. Bukod dito, nagsagawa rin ng isang medical mission kung saan nagbigay ng libreng gamot, nagsagawa ng blood pressure monitoring, at iba pang serbisyong pangkalusugan upang masiguro ang kanilang kalagayan at kapakanan.
Ang inisyatibong ito ay isinagawa kasama ang founder ng Universidad de Dagupan, Dr. Voltaire P. Arzadon, Supreme Student Council, Adviser Ma’am May Jacklyn R. Samson at ang University President, Dr. Feliza Arzadon-Sua. At taos-pusong pasasalamat sa lahat ng UDD Administration para sa kanilang walang sawang suporta. Sa makabuluhang pagdiriwang na ito, ating kinikilala na ang kagitingan ay hindi lamang nakaukit sa mga pahina ng kasaysayan, kundi buhay rin sa araw-araw na pagsusumikap ng ating mga makabagong bayani—mga drayber na patuloy na humaharap sa hamon ng kalsada nang may katatagan, pasensya, at buong pusong dedikasyon.
Sa pamamagitan ng inisyatibong ito, muli tayong pinaaalalahanan na ang tunay na tapang ay naipapakita sa mga gawa ng malasakit, paglilingkod, at paninindigan para sa kapwa. Nawa’y magsilbi itong inspirasyon upang patuloy nating kilalanin at suportahan ang mga taong tahimik ngunit mahalagang nagpapatakbo sa ating mga komunidad.
Back to All News


--- Source 26 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/119

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
SDG 1 - GOOD HEALTH AND WELL BEING
UDD Expands Community Care Through Medical Mission 2026
By UdD Staff
Mar 31, 2026
Share
Building on our promise to bring healthcare closer to home, the Universidad de Dagupan Medical Mission 2026 has officially come to life! Following our launch of "Alagang Pangkalusugan para sa Paaralan at Komunidad," this day stands as a heartfelt fulfillment of our commitment to the people of Dagupan. At the forefront of this mission, the 𝗖𝗮𝗺𝗽𝘂𝘀 𝗣𝗿𝗶𝗺𝗮𝗿𝘆 𝗥𝗲𝘀𝗽𝗼𝗻𝗱𝗲𝗿𝘀 (𝗖𝗣𝗥) took the lead, transforming our vision of "United for Health, Serving with Heart" into a reality through their dedicated leadership and technical expertise.
By bridging the gap between medical professionals and the community, the CPR—together with our faculty, students, and esteemed partners—ensured that every individual had access to vital free services. From medical consultations and essential medications to specialized ECGs, X-rays, eye check-ups, and the Yakap Program, the mission successfully catered to the diverse needs of our fellow Dagupeños. The inclusion of a blood donation drive and circumcision (tuli) services further emphasized our collective goal of promoting long-term wellness and saving lives.
This event was made possible through the unwavering support of the Region 1 Medical Center, Dagupan Doctors Villaflor Memorial Hospital, Philippine Red Cross, and our many dedicated partners and local leaders. More than just a one-day clinic, this initiative, spearheaded by the Campus Primary Responders, serves as a powerful movement of compassion. Together, we continue to prove that when we serve with purpose and care with heart, we truly heal as one.
Back to All News


--- Source 27 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/118

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
SDG 15 - LIFE ON LAND
UDD STUDENT LEADERS LAUNCH THE “GINHAWA SA PASADA” PROJECT
By UdD Staff
Mar 23, 2026
Share
On this day, March 23, 2026, the Supreme Student Council took to the streets of Dagupan to launch the "Ginhawa sa Pasada" project. Aimed at providing comfort to jeepney and tricycle drivers affected by the recent spike in fuel prices, the council distributed essential relief kits to help ease the physical demands of their daily routes.
We believe that leadership is defined by service to the community. Although this is just a small act of kindness, we hope it sparks a larger conversation regarding the welfare of our local drivers. We invite other organizations to join us in supporting the sectors most impacted by the current economic climate.
We would also like to express our deepest gratitude to the Universidad de Dagupan Administration for their never-ending support of our initiatives. Your guidance allows us to extend our mission beyond the campus and directly into the hearts of our community
Back to All News


--- Source 28 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/117

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
SDG 15 - LIFE ON LAND
UDD Receives Prestigious DSWD Special Citation as Development Partner
By UdD Staff
Mar 19, 2026
Share
With hearts full of gratitude, Universidad de Dagupan sincerely thanks the Department of Social Welfare and Development (DSWD) for the Special Citation as a Development Partner Supporting DSWD Centers and Residential Care Facilities. This recognition inspires us to continue fostering compassion, inclusivity, and meaningful community engagement. All glory to God for this milestone as we remain committed to serving with excellence and purpose.
Back to All News


--- Source 29 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/events/2

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus
Orientation for Freshmen and Transferees.
By Administrator
March 1, 2023
Share
Orientation for Freshmen and Transferees.
This aims to let students be familiar with the policies and procedures of the university.
Back to All Events


--- Source 30 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/events/7

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus
Light Up the Night! UdD Celebrate Our 2nd Uni Anni Lighting Ceremony
By UdD Staff
December 14, 2023
Share
The Universidad de Dagupan (UdD) community recently came together for a spectacular celebration – the 2nd Uni Anni Lighting Ceremony! The event marked the university's second year of fostering academic excellence, community engagement, and student success.
Students gathered together to witness another moment to be remembered. The atmosphere filled with exciting cheers and chants as students count down from 10 to 1 for the ultimate highlight of the night. After that, the night was filled with breathtaking LED lights, filling-up the whole UdD campus quadrangle. With such moments like these, the school transformed into a vibrant spectacle of lights, music, and celebration.
The 2nd Uni Anni Lighting Ceremony was more than just a celebration; it was a testament to UdD's commitment to providing a transformative educational experience for its students. It was an opportunity to celebrate UdD’s achievements, milestones and accomplishments over the past year were acknowledged with pride. The ceremony served as a springboard for embracing the exciting possibilities that lie ahead for UdD and its students. Coming together as a community, faculty, staff, students, alumni, and supporters strengthened the bonds of unity and pride within the UdD community.
The 2nd Uni Anni Lighting Ceremony was a resounding success, leaving a lasting impression on everyone who witnessed its brilliance.
Back to All Events


--- Source 31 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/events/4

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus
Maliket ya Agew na Dagupan!
By Administrator
June 20, 2023
Share
“𝘌𝘷𝘦𝘳𝘺 𝘷𝘰𝘭𝘶𝘯𝘵𝘦𝘦𝘳𝘴 𝘰𝘧 𝘰𝘶𝘳 𝘊𝘪𝘵𝘺 𝘳𝘦𝘧𝘭𝘦𝘤𝘵𝘴 𝘵𝘩𝘦 𝘵𝘳𝘶𝘦 𝘩𝘦𝘢𝘳𝘵 𝘰𝘧 𝘢 𝘋𝘢𝘨𝘶𝘱𝘦ñ𝘰.” –Mayor Belen Fernandez
𝐌𝐚𝐥𝐢𝐤𝐞𝐭 𝐲𝐚 𝐀𝐠𝐞𝐰 𝐧𝐚 𝐃𝐚𝐠𝐮𝐩𝐚𝐧!
June 20, 1947 when President Manuel Roxas signed Republic Act 170 officially recognizing Dagupan as a city.
As we celebrate the city's 76th anniversary, the city charter of Dagupan, NSTP students of Universidad de Dagupan organized a clean up drive at Bonuan Tondaligan beach as our way of support in the celebration of the aforementioned.
The said activity is spearheaded by Dr. Feliza Arzadon-Sua, our University President and one of the Pinabling Pangidayew na Mayor Diamond Awardee of Dagupan City.
https://www.facebook.com/UdDSSC/posts/pfbid02tTSpeTj5ENsT2u3CnJnzWfdesuFVP6DzeH1iwrWjgsybXZyfP2Jk7WJMnjYST8vql
Back to All Events


--- Source 32 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/events/5

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus
Freshmen Kick-Off Orientation 2023: U Dare to Dream!
By UdD Staff
September 9, 2023
Share
Universidad de Dagupan is back at it again with its annual Freshmen Kick-Off Orientation, an event designed to welcome and guide incoming freshmen into the exciting world of UdD!
The program began with a dynamic showcase of talent and energy. Introducing the School of Information Technology Education (SITE) Pep Squad -- 2023 UDD CheerDance Champion, Koro Universidad, and Steed Dance Company with their actively engaging intermission performances that had the audience standing and cheering.
But that’s not all, the fun has just begun! Following the exhilarating performances, is a raffle draw, where a whopping 100 tablets were given away to lucky students. This was followed by a celebratory parade honoring the Intramurals 2023 Champions, and the prestigious awarding of Presidential Scholars for the academic year. These achievements added a sense of accomplishment and pride to the entire occasion.
Beyond the formal ceremonies, the event offered a taste of the lively campus life at UdD. Students enjoyed a Mini Banda Mania and Disco Party, a refreshing dip in the pool, and fun parlor games.
Additionally, this tremendous event gave freshmen students an inside-look of what UdD is all about. Students got a firsthand glimpse into the vibrant campus culture, diverse student organizations, and unmatched energy from each department with each of their own unique booths that make UdD one of a kind.
Freshmen students also got the opportunity to forge friendships and built a strong foundation amongst their fellow peers that will surely last throughout their college journey.
The Universidad de Dagupan Freshmen Kick-Off Orientation is more than just an introduction. It's a chance to step into a world of possibilities, embrace new challenges, and embark on an unforgettable adventure filled with academic excellence, personal growth, and lasting friendships.
Back to All Events


--- Source 33 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/16

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
SDG 5 - DECENT WORK AND ECONOMIC GROWTH
UdD first ever escalator
By UdD Staff
Jun 3, 2024
Share
UdD Founder and Chairman of the Board, Dr. Voltaire P. Arzadon, spearheaded theinauguration of the first ever escalator of the campus. UdD stands out as the only school in Pangasinan and one of the few in the country equipped with both escalators and elevators.
This is very convenient and accessible to our students and employees during their class hours.
Back to All News


--- Source 34 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/15

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
SDG 8 - REDUCED INEQUALITIES
UdD is PWD Friendly
By UdD Staff
Sep 23, 2022
Share
By enhancing the facilities that meet their needs, UNIVERSIDAD DE DAGUPAN is facilitating the attendance of persons with disabilities (PWDs) in their classes.
PWD students and staff may now be easily transported across the UdD main campus thanks to upgraded wheelchair ramps, a new lifter, and an existing elevator. Similarly, PWD students and clients must have spaces and waiting areas in offices and student service centers.
Back to All News


--- Source 35 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/14

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
SDG 1 - ZERO HUNGER
UdD Pamaskong Handog brings joy to families in Dagupan City
By UdD Staff
Dec 22, 2023
Share
Universidad de Dagupan led by the Chairman of the board of trustees Dr. Voltaire P. Arzadon to witness the distribution of the donation for the selected families.
Universidad de Dagupan's PAMASKONG HANDOG was a touching event that embodied the bayanihan and Christmas spirit as staff and students came together to cheer up a few families in Dagupan City.
Under the leadership of the Supreme Student Council, this project demonstrated solidarity as many student officers and organizations worked together harmoniously. The occasion served as evidence of the strength of group generosity and the dedication of the university community to have a positive influence over the holidays. This said project is to give importance to the families and to ease their burden, especially on Christmas. In this small gift, we bring joy and a merry Christmas for them.
Back to All News


--- Source 36 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/news/4

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Update
UdD appoints Dr. Arzadon-Sua as new president
By Administrator
Mar 28, 2023
Share
UdD appoints Dr. Arzadon-Sua as new president
Dr. Feliza Arzadon-Sua has been appointed as the new president of Universidad de Dagupan taking over the position from her father, Dr. Voltaire P. Arzadon, who served the institution for 39 years.
Atty. Joseph Noel Estrada, UdD’s Legal counsel, awarded the appointment along with the Board of Trustees. While the University Medallion and Mace were handed by the 1st and outgoing president, Dr. Voltaire P. Arzadon.
Dr. Arzadon-Sua is the university’s first female president. She first served as an internal auditor and later became the Vice President for Administration and Vice President for Academic Affairs of the institution.
In her acceptance speech, Dr. Arzadon-Sua highlighted her goals for the institution namely, fostering meaningful connections, enriching learning and word environment, leveraging UdD’s strengths, implementing employment initiatives for graduates, encouraging zeal for service and administration, and achieving international and national distinctions.
The turnover and investiture ceremonies was held on March 23, 2023 at UdD-Arzadon Gymnasium, Leisure Coast Resort and were attended by different officials from CHED, DepEd, LGUs, members of the university administration, faculty, staff, and students.
The event set the beginning of a new chapter for Universidad de Dagupan.
Back to All News


--- Source 37 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/events/8

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus
UdD Celebrates 2nd Year as a University: Another Year of Recollection
By UdD Staff
December 18, 2023
Share
The University of Dagupan (UdD) marked a significant milestone last December 14, 2023, celebrating its second Uni-anniversary as a full-fledged university. This momentous occasion signifies not only the institution's continued growth and development but also the ongoing construction of a legacy of academic excellence and community engagement.
UdD's journey towards university status began in 1984, when it was established as “Computronix”. Over the years, the institution steadily expanded its academic offerings, research initiatives, and community outreach programs. This dedication to progress culminated in 2021 when UdD officially gained university status, marking a new chapter in its history.
The past two years have been a period of significant transformation for UdD. The university has implemented various initiatives to strengthen its academic programs, including the introduction of new degree courses, the expansion of research facilities, and the recruitment of highly qualified faculty members. Additionally, UdD has actively engaged with the local community through various outreach programs, fostering partnerships and contributing to the social and economic development of the region.
As UdD celebrates its second anniversary as a university, it stands poised for further growth and success. The campus buzzed with excitement as students, faculty, and staff came together for a whirlwind of festivities.
Booths proudly displayed student achievements and creativity, showcasing the university's vibrant academic and extracurricular life. Aromatics filled the air from a vast array of food stalls, offering a delicious feast for all. Stellar performances kept the energy high throughout the day, with talented students taking the stage and captivating the crowd.
But the undisputed highlight of the event was the Bandmania, the epic battle of the bands! Students from different school departments brought the house down with their musical prowess, raw energy, and fierce school spirit. In a thrilling competition, the School of Humanities (SOH) emerged victorious, solidifying their place as UdD's musical champions.The celebration was a resounding success, leaving everyone excited for the university's bright future.
The institution's commitment to academic excellence, community engagement, and innovation promises a bright future for UdD and its students. This anniversary serves as a testament to the hard work and dedication of the UdD community, and it marks the beginning of a new era for the university as it continues to build a strong and lasting legacy.
Back to All Events


--- Source 38 ---
Title: Universidad de Dagupan | Formerly Colegio de Dagupan

Source: https://udd.edu.ph/events/6

---

Skip to main content
12 }"
@scroll.window="scrolled = window.scrollY > 12"
@keydown.escape.window="mobileMenuOpen = false; campusMenuOpen = false"
class="fixed inset-x-0 top-0 z-50"
The first ISO 21001:2018-certified university in Region 1
Document Request
STEP LMS
UdD Portal
e-Thesis
Universidad de Dagupan
Formerly Colegio de Dagupan
Universidad de Dagupan
Student portals
UdD Portal
STEP LMS
Campus
Pamaskong Handog 2023: Spreading Holiday Cheer One Blessing at a Time.
By UdD Staff
December 13, 2023
Share
The Universidad de Dagupan (UdD) ushered in the holiday season with its heartwarming "Pamaskong Handog 2023" initiative, organized by the Supreme Student Council under the theme "Liwanag ng Pasko, Kasiyahan sa Bawat Puso" (Light of Christmas, Joy in Every Heart). This event served as a beautiful reminder of the importance of compassion, generosity, and the spirit of giving during the festive season.
UdD's "Pamaskong Handog" brought together students, faculty, and staff in a collective effort to bring joy and support to those in need. The initiative involved various activities, including giving gifts to ones in need. UdD prepared and distributed gift packages filled with essential items and holiday treats to underprivileged families and individuals in the community.
The impact of "Pamaskong Handog 2023" extended far beyond the material gifts. The event fostered a strong sense of unity and compassion within the UdD community. Students, faculty, and staff came together as a single unit, dedicating their time and effort to make a positive difference in the lives of others. This spirit of giving truly embodied the essence of the holiday season.
"Pamaskong Handog" left a lasting impression on everyone involved. It served as a powerful reminder of the joy that comes from giving back and the importance of spreading holiday cheer during this special time of year. The initiative is a testament to UdD's unwavering commitment to social responsibility and its dedication to making a positive impact on the community.
Back to All Events

`;
